locals {
  log_groups = {
    messages = "/bfd/${var.env}/bfd-pipeline/messages.txt"
  }
  metrics = {
    G1_Old_Generation_count                        = "[..., name=*G1-Old-Generation.count*, value=*]"
    G1_Old_Generation_time                         = "[..., name=*G1-Old-Generation.time*, value=*]"
    G1_Young_Generation_count                      = "[..., name=*G1-Young-Generation.count*, value=*]"
    G1_Young_Generation_time                       = "[..., name=*G1-Young-Generation.time*, value=*]"
    HikariPool_1_pool_ActiveConnections            = "[..., name=*HikariPool-1.pool.ActiveConnections*, value=*]"
    HikariPool_1_pool_IdleConnections              = "[..., name=*HikariPool-1.pool.IdleConnections*, value=*]"
    HikariPool_1_pool_MaxConnections               = "[..., name=*HikariPool-1.pool.MaxConnections*, value=*]"
    HikariPool_1_pool_MinConnections               = "[..., name=*HikariPool-1.pool.MinConnections*, value=*]"
    HikariPool_1_pool_PendingConnections           = "[..., name=*HikariPool-1.pool.PendingConnections*, value=*]"
    HikariPool_1_pool_TotalConnections             = "[..., name=*HikariPool-1.pool.TotalConnections*, value=*]"
    heap_committed                                 = "[..., name=*heap.committed*, value=*]"
    heap_init                                      = "[..., name=*heap.init*, value=*]"
    heap_max                                       = "[..., name=*heap.max*, value=*]"
    heap_usage                                     = "[..., name=*heap.usage*, value=*]"
    heap_used                                      = "[..., name=*heap.used*, value=*]"
    non_heap_committed                             = "[..., name=*non-heap.committed*, value=*]"
    non_heap_init                                  = "[..., name=*non-heap.init*, value=*]"
    non_heap_max                                   = "[..., name=*non-heap.max*, value=*]"
    non_heap_usage                                 = "[..., name=*non-heap.usage*, value=*]"
    non_heap_used                                  = "[..., name=*non-heap.used*, value=*]"
    pools_CodeHeap_non_nmethods_committed          = "[..., name=*pools.CodeHeap-'non-nmethods'.committed*, value=*]"
    pools_CodeHeap_non_nmethods_init               = "[..., name=*pools.CodeHeap-'non-nmethods'.init*, value=*]"
    pools_CodeHeap_non_nmethods_max                = "[..., name=*pools.CodeHeap-'non-nmethods'.max*, value=*]"
    pools_CodeHeap_non_nmethods_usage              = "[..., name=*pools.CodeHeap-'non-nmethods'.usage*, value=*]"
    pools_CodeHeap_non_nmethods_used               = "[..., name=*pools.CodeHeap-'non-nmethods'.used*, value=*]"
    pools_CodeHeap_non_profiled_nmethods_committed = "[..., name=*pools.CodeHeap-'non-profiled-nmethods'.committed*, value=*]"
    pools_CodeHeap_non_profiled_nmethods_init      = "[..., name=*pools.CodeHeap-'non-profiled-nmethods'.init*, value=*]"
    pools_CodeHeap_non_profiled_nmethods_max       = "[..., name=*pools.CodeHeap-'non-profiled-nmethods'.max*, value=*]"
    pools_CodeHeap_non_profiled_nmethods_usage     = "[..., name=*pools.CodeHeap-'non-profiled-nmethods'.usage*, value=*]"
    pools_CodeHeap_non_profiled_nmethods_used      = "[..., name=*pools.CodeHeap-'non-profiled-nmethods'.used*, value=*]"
    pools_CodeHeap_profiled_nmethods_committed     = "[..., name=*pools.CodeHeap-'profiled-nmethods'.committed*, value=*]"
    pools_CodeHeap_profiled_nmethods_init          = "[..., name=*pools.CodeHeap-'profiled-nmethods'.init*, value=*]"
    pools_CodeHeap_profiled_nmethods_max           = "[..., name=*pools.CodeHeap-'profiled-nmethods'.max*, value=*]"
    pools_CodeHeap_profiled_nmethods_usage         = "[..., name=*pools.CodeHeap-'profiled-nmethods'.usage*, value=*]"
    pools_CodeHeap_profiled_nmethods_used          = "[..., name=*pools.CodeHeap-'profiled-nmethods'.used*, value=*]"
    pools_Compressed_Class_Space_committed         = "[..., name=*pools.Compressed-Class-Space.committed*, value=*]"
    pools_Compressed_Class_Space_init              = "[..., name=*pools.Compressed-Class-Space.init*, value=*]"
    pools_Compressed_Class_Space_max               = "[..., name=*pools.Compressed-Class-Space.max*, value=*]"
    pools_Compressed_Class_Space_usage             = "[..., name=*pools.Compressed-Class-Space.usage*, value=*]"
    pools_Compressed_Class_Space_used              = "[..., name=*pools.Compressed-Class-Space.used*, value=*]"
    pools_G1_Eden_Space_committed                  = "[..., name=*pools.G1-Eden-Space.committed*, value=*]"
    pools_G1_Eden_Space_init                       = "[..., name=*pools.G1-Eden-Space.init*, value=*]"
    pools_G1_Eden_Space_max                        = "[..., name=*pools.G1-Eden-Space.max*, value=*]"
    pools_G1_Eden_Space_usage                      = "[..., name=*pools.G1-Eden-Space.usage*, value=*]"
    pools_G1_Eden_Space_used                       = "[..., name=*pools.G1-Eden-Space.used*, value=*]"
    pools_G1_Eden_Space_used_after_gc              = "[..., name=*pools.G1-Eden-Space.used-after-gc*, value=*]"
    pools_G1_Old_Gen_committed                     = "[..., name=*pools.G1-Old-Gen.committed*, value=*]"
    pools_G1_Old_Gen_init                          = "[..., name=*pools.G1-Old-Gen.init*, value=*]"
    pools_G1_Old_Gen_max                           = "[..., name=*pools.G1-Old-Gen.max*, value=*]"
    pools_G1_Old_Gen_usage                         = "[..., name=*pools.G1-Old-Gen.usage*, value=*]"
    pools_G1_Old_Gen_used                          = "[..., name=*pools.G1-Old-Gen.used*, value=*]"
    pools_G1_Old_Gen_used_after_gc                 = "[..., name=*pools.G1-Old-Gen.used-after-gc*, value=*]"
    pools_G1_Survivor_Space_committed              = "[..., name=*pools.G1-Survivor-Space.committed*, value=*]"
    pools_G1_Survivor_Space_init                   = "[..., name=*pools.G1-Survivor-Space.init*, value=*]"
    pools_G1_Survivor_Space_max                    = "[..., name=*pools.G1-Survivor-Space.max*, value=*]"
    pools_G1_Survivor_Space_usage                  = "[..., name=*pools.G1-Survivor-Space.usage*, value=*]"
    pools_G1_Survivor_Space_used                   = "[..., name=*pools.G1-Survivor-Space.used*, value=*]"
    pools_G1_Survivor_Space_used_after_gc          = "[..., name=*pools.G1-Survivor-Space.used-after-gc*, value=*]"
    pools_Metaspace_committed                      = "[..., name=*pools.Metaspace.committed*, value=*]"
    pools_Metaspace_init                           = "[..., name=*pools.Metaspace.init*, value=*]"
    pools_Metaspace_max                            = "[..., name=*pools.Metaspace.max*, value=*]"
    pools_Metaspace_usage                          = "[..., name=*pools.Metaspace.usage*, value=*]"
    pools_Metaspace_used                           = "[..., name=*pools.Metaspace.used*, value=*]"
    total_committed                                = "[..., name=*total.committed*, value=*]"
    total_init                                     = "[..., name=*total.init*, value=*]"
    total_max                                      = "[..., name=*total.max*, value=*]"
    total_used                                     = "[..., name=*total.used*, value=*]"
  }
}

resource "aws_cloudwatch_log_metric_filter" "bfd-pipeline-metrics" {
  for_each       = local.metrics
  name           = "${each.key}"
  pattern        = "${each.value}"
  log_group_name = local.log_groups.messages

  metric_transformation {
    name          = "/bfd-${var.env}/bfd-pipeline/${each.key}"
    namespace     = "/bfd-${var.env}/bfd-pipeline"
    value         = "$value"
    default_value = "0"
  }
}
